### ISSUE TITLE
FlexToolbar: not able to collapse searchfield nor only have title and buttonset sections

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise-ng#1225]
**Describe the bug**
A while back we requested support for centered search in the toolbar, which was implemented [in this Enterprise issue](https://github.com/infor-design/enterprise/pull/5958). 

@ericangeles said he would [create an example](https://github.com/infor-design/enterprise/pull/5958#issuecomment-996469134) for enterprise-ng, but I didn't see anything in enterprise-ng changelog for that, so it migth have been lost though along the way? :)

Anyway, after our upgrade now, I saw that the searchfield that we use in the standard way, i.e. not centered, is not working as previously. They are no longer collapsed, which potentially could have an impact on multiple teams (not sure how it currently looks in enterprise project if you can collapse it there with this new styles?). 
Also, the spacing between title and buttonset section is not working as expected. See image. Edit: Also 2, the placeholder text color seems wrong.

**To Reproduce**
1. Go to [this Stackblitz](https://stackblitz.com/edit/ids-quick-start-1301-xcd9eu?file=src%2Fapp%2Fheader%2Fheader.component.ts)
2. See first issue uncommented, where the searchfield is not collapsed (even though it has `[collapsible]="true"` set.
3. In .html comment in the first "Issue  1" and comment out the "Issue 2" code.
4. Now you can see the spacing issue for when you only have a title and buttonset section.

**Expected behavior**
- Searchfield should be able to collapse (like before for standard flex-toolbars with search).
- If one has a centered searchfield (which currently there is nothing specific in the enterprise-ng API to do so, I assume just the "correct" markup is needed), then the collapse does not necessarily need to support callapsing.  
- You should be able to have only a title section and a buttonset section, with correct spacing between.

**Version**
- ids-enterprise-ng: 13.1.1

**Screenshots**
1. Searchfield not collapsible
![image](https://user-images.githubusercontent.com/73601152/151957962-825b3158-8754-4f28-8a9c-119d4b785437.png)

2. Spacing between title and a buttonset section is not working:
![image](https://user-images.githubusercontent.com/73601152/151958050-2c0e96b3-49a9-45e8-9c59-75070a0f2305.png)

**Platform**
 - OS Version: OSX
 - Browser Name Firfox
 - Browser Version 96.0.3

**Comment by tmcconechy** [comment]
This looks a lot like https://github.com/infor-design/enterprise/issues/6039 which was patched into 4.59.2
Could you folks test this? I tried to update the stackblitz to 13.0.3 which should have this fix...

But this seems like the same issue... and that flex rule was removed to fix it.

**Comment by whernebrink** [comment]
Installed 13.0.3 on the stackblitz and locally, same result.

**Comment by tmcconechy** [comment]
Ok yeah that’s what’s wierd I think maybe the button issue is fixed but with the searchfield there are more issues yet

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles 
Hello, I tried reproducing the buttonset spacing bug in local and the buttons in the header align correctly. I also checked to see if the "display: flex" shown here: https://github.com/infor-design/enterprise-ng/issues/1225#issuecomment-1027751627 is in the header css since that seems to be the cause for the left alignment, but I couldn't find it.
<img width="1792" alt="Screen Shot 2022-03-03 at 4 09 34 PM" src="https://user-images.githubusercontent.com/85279127/156523462-b152d87a-db88-4076-8f1d-6224f860739b.png">

**Comment by whernebrink** [comment]
@yohannahbautista which example are you running? Mine look very different: 
![image](https://user-images.githubusercontent.com/73601152/156534514-9b7043a6-954e-4e51-966f-10fd4254c901.png)

However, seems like the spacing issue with title and buttonset does not exist anymore, but the searchfield issue is still there. Here is an updated stackblitz which runs 13.1.0 and 4.60 of EP.
https://stackblitz.com/edit/ids-quick-start-1311-tw8bry?file=src%2Fapp%2Fapp.component.ts

**Comment by tmcconechy** [comment]
@yohannahbautista @ericangeles - does this have any additional fixes ? I'm not seeing them attached / so not sure the present state

**Comment by yohannahbautista** [comment]
@whernebrink @tmcconechy @ericangeles 
Hello, for the collapsible searchfield, my PR for a fix is already merged so the latest version should fix the bug. I made another PR that includes new example pages to test the searchfield: https://github.com/infor-design/enterprise-ng/pull/1251

**Comment by yohannahbautista** [comment]
> @yohannahbautista which example are you running? Mine look very different: ![image](https://user-images.githubusercontent.com/73601152/156534514-9b7043a6-954e-4e51-966f-10fd4254c901.png)
> 
I just edited one of the existing header pages to make it as similar to the example to stackblitz as possible (which was mostly just removing the buttons in toolbar example page I think)

**Comment by tmcconechy** [comment]
Should be ok in 4.61 now - closing
