### ISSUE TITLE
Datagrid: updatePagingInfo is not defined when running outside of angular

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise-ng#285]
**Describe the bug**
When trying to set the page of the data grid it is unable to find the function when running outside of angular.

**To Reproduce**
try running this.datagrid.updatePagingInfo({activePage: 2});
https://github.com/infor-design/enterprise-ng/blob/cdbedcb485ad466b097aa06879a59e25ec6b3483/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1204

**Expected behavior**
the page should be updated to the second page

**Version**
- ids-enterprise-ng:  v4.12.1

**Comment by tmcconechy** [comment]
Can you clarify the steps to reproduce? Im not certain what you mean. Maybe attach an updated script we can drop in.

**Comment by tmcconechy** [comment]
Enable to reproduce this so closing

**Comment by EdwardCoyle** [comment]
Re-opening due to more context [provided via MS Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1554297249366?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1554297249366&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1554297249366)

At a glance, I think there's an issue in the Angular Component wrapper.  This code in particular:
https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/datagrid/soho-datagrid.component.ts#L1235-L1239

There is no `updatePagingInfo()` method on the IDS Datagrid API.  That method is actually on [the Pager component](https://github.com/infor-design/enterprise/blob/master/src/components/pager/pager.js#L1288-L1302), and is called inside the Datagrid API in the `renderPager()` method.  I think the wrapper should probably change to reflect this, and we may see it start working again.

**Comment by AnaLauraMartinez** [comment]
[DataCatalog - Google Chrome 4_3_2019 9_32_29 AM.zip](https://github.com/infor-design/enterprise-ng/files/3039215/DataCatalog.-.Google.Chrome.4_3_2019.9_32_29.AM.zip)

**Comment by tmcconechy** [comment]
Noting that the way the newer EP examples do this is 
```
        gridAPI.triggerSource({
          activePage: 2
        });
```
But thats for server side paging. Going to add the function back in like this. So it can be called on the pager.

```
    component.datagrid.pagerAPI.updatePagingInfo({
      activePage: 1,
      type: 'next'
    });
```

Im not able to reproduce the issue from @AnaLauraMartinez as all it is is a video. So will need a new issue to be created with steps and a way to reproduce it if its not fixed by this change.

**Comment by AnaLauraMartinez** [comment]
I retested in 7.1 and still the same issue. I will try to build a test for this. 
Steps for us:
1. Go to page 3
2. Drill down
3. Click back button
4. page is reset to 1

**Comment by tmcconechy** [comment]
That sound app specific. So what is all that doing? Yeah maybe build a test page we can run
